module.exports = {
  //email setting
  AUTH_KEY: "205521AaBNspcwGS5ab512aa",
  FROM: "info@samyotech.com",
  //Verified Url
  VERIFIED_EMAIL: "http://159.65.157.119:4005/verify-email/",
  UPDATE_EMAIL: "http://159.65.157.119:4005/update_email/",
  update_email_msg: "<br/>Do you want to change the email id so please click this link. ",
  ACCOUNT_STATUS: 'It seems that your account has been deactivated from admin. Please contact admin to resume your account. Thank You.',
  chkfield: "check all fields.",
  verifyUpdateEmail: "Please verify your email id.",
  ERR: "Please try again after some time.",
  USER_NOT_FOUND: "User not found",
  DEACTIVATEUSER: "You are not active user",
  VerifyEmail: "Please verify your email id.",
  getUserData: "Get user profile.",
  DeleteAcc: "Delete account.",
  getAllWork: "Get all work.",
  updateEmail: "Update email successfully.",
  updateMobile: "Update mobile number successfully.",
  //  LOGINSUCCESSFULL:"تسجيل الدخول بنجاح ",
  LOGINSUCCESSFULL: "Login Successfully.",
  Nocoupon: "No coupon available.",
  getAllCoupon: "Get all coupons.",
  ALL_NOTIFICATION: "Get All Notifications.",
  logout: "Logout Successfully.",
  EMAILALERADY: "Email id is already exist,please enter any ohter id.",
  //  REG_SUCCESS:"Registration Successfully.Please verify your email id.",
  REG_SUCCESS: "Registration successful. We’ve sent you an email message to verify your email id before you login.",
  CHECK_YOUR_EMAIL: "Check your email Id.",
  User_INFO_UPDATE: "User information updated.",
  ACCOUNT_STATUS: "It seems that your account has been deactivated from admin. Please contact admin to resume your account. Thank You.",
  NO_VALUE_SEND: "No value send.",
  PASS_NT_MATCH: "Invalid Password.",
  FORGETPASS: "Your password has been changed Successfully.",
  NOT_RESPONDING: "Please try again later.",
  NOT_MATCHED: "Old password does not match.",
  PWD_CNG: "Please check your email for updated Password.",
  EMAILIDNOTFOUND: "Email id is not found.",
  PROFILE_UPDATED: "Profile has been updated successfully.",
  GET_CAT: 'Get all categories.',
  deleteService: "Deleted service.",
  NO_CAT: 'No data available.',
  NOEMAIL: "Email does not exist.",
  POST_JOB: "Job added successfully.",
  ADD_RATING: "Rating given successfully.",
  // NOT_RESPONDING: "Please try again later.",
  JOB_UPDATE: 'Job updated Successfully.',
  JOB_DELETE: 'Job deleted Successfully.',
  ARTIST_WORKING: "Currently artist working on this job.",
  ADD_GALLERY: "Gallery updated successfully.",
  Zero: 0,
  One: 1,
  TWo: 2,
  NOT_RESPONDING: "Please try again later.",
  JOB_START: "Job start successfully.",
  JOB_UPDATE: 'Job updated Successfully.',
  JOB_DELETE: 'Job deleted Successfully.',
  JOB_CONFIRM: 'Job confirmed Successfully.',
  JOB_REJECTED: 'Job rejected Successfully.',

  APPLIED_JOB: "Job applied successfully.",
  Applied_job_title: "Job Applied.",
  APPLIED_JOB_MSG: "Applied on your job.",
  base_url_image: "http://159.65.241.51/",
  base_url: "http://159.65.241.51/",
  status: "status",
  message: "message",
  AlredyRegister: " User already registered .",
  USER: "user",
  GET_JOB: 'Get all jobs.',
  MSGUPDATEDPASSWORD: "Your updated password is",
  TIECKET_GENERATED: "Ticket generated successfully.",
  MY_TIECKET: "Get my tickets.",
  ADD_COMMENT: "Comment added successfully.",
  getAllRating: "Get all ratings.",
  getAllService: "Get all services.",
  NODATA: 'No data available.',
  Notification_type: "10001",
  Accept_Job: "10002",
  Delete_job: "10003",
  Complete_job: "10004",
  Start_job: "10005",
  end_job: "10006",
  reject_job_type: "10008",
  post_job_type: "1111",
  chat_type1: "20001",
  Direct_Job: "10009",
  Applied_job: "10010",
  invoice_type: "10011",
  review_type: "10012",
  Apply_job_title: "Applied Job.",
  START_JOB: "Job started successfully.",
  StartJobByArtist: "Artist has been started your job",
  Direct_Job_msg: "You have get a new job.",
  Accept_Job_msg: "Job accepted successfully.",
  Reject_job: "Job rejected successfully.",
  jobRunning: "Your job is in working mode.",
  Reject_title: "Rejected job.",
  deleteGallery: "Delete Gallery successfully.",
  Invoice_created: "Paid your invoice.",
  review_msg: "Someone gives you rating.",
  review_title: "Rating.",
  end_job_succ: "Job ended successfully.",
  pending_job: "Get all pending jobs.",
  confirmJob: "Get all confirm jobs.",
  incorrectPwd: "Please enter correct password.",
  Apply_job: "Get all users who has applied this job.",
  Not_Job_Apply: "Not Apply job Data found.",
  AccepJotTitle: "Accepted job.",
  getCompleteJob: "Get all complete jobs.",
  getRejectJob: "Get all reject jobs.",
  getDeactivejob: "Get all deactive jobs.",
  runningJob: "Get all running Jobs.",
  jobDone: "Job done.",
  CURRENT_APPOINTMENT: "Get my current Appointment.",
  GET_ARTIST_NEAR: "Get all artists.",
  Job_reject: "Reject job.",
  Job_reject_msg: "Rejected job by user.",
  Job_reject_msg_artist: "Rejected job by artist.",
  getAllData: "Get all data.",
  Completejob: "Complete job",
  insufficient: "You don't have sufficient point to pay for this job.",
  completeJobMsg: "Completed your job by artist.",
  Delete_job_title: "Deleted job.",
  getAllArtist: "Get all artist.",
  Delete_msg: "Job deleted By user",
  NOT_FOUND_DATA: "Not found data.",
  newJob: "New Job",
  startJob: "Start job.",
  alreadyCouponUsed: "Already coupon used.",
  ActiveJob: "All active jobs",
  AlredyRegisterWithNormal: "Already registered with normal mode.",
  GetAllInvoice: "Get all invoice data",
  timeMsg: "You can't create a job on same time.",
  //name of the all Apis
  GetInvoice: "/getInvoice",
  GetNearestArtist: "/getNearArtist",
  GetCurrentJob: "/getCurrentJob",
  GetAllActiveJobs: "/getAllActivebookingJob",
  EndJob: "/EndJob",
  StartJob: "/startJob",
  AcceptJobByUser: "/AcceptJobByUser",
  GetJobsAppliedByUser: "/getJobsAppliedUser",
  GetJobsArtist: "/getJobsArtist",
  ApplyJob: "/applyJob",
  GetJobByStatus: "/getJobsByStatus",
  Deletejob: "/deletejob",
  UpdateJob: "/updateJob",
  GetMyJobs: "/getMyJobs",
  PostJob: "/postJob",
  SignUp: "/signUp",
  SignUp1: "/signUpByOnline",
  SignIn: "/signIn",
  changePassword: "/changePassword",
  fogetPassword: "/fogetPassword",
  updateProfile: "/updateProfile",
  checkSocialLogin: "/checkSocialLogin",
  CHAT_HISTORY: "Get my chat history.",

  MSGSENDSUCCESS: "Message send successfully.",
  HELLO: "Hello",
  REGISTRATION_TXT: "<br/> Thank you for registration with artBeatz App. Please click on below link for verify you email address.",
  RGN: "Registration",
  email_update: "Update Email.",
  SIGNATURE: "<br/> Thanks, <br/>artBeatz Team",
  FRGPWD: "Forgot Password",
  All_Coupons: "Get All Coupons.",
  No_data: "No Data Found.",
  ADD_SERVICE: "Add Service Successfully.",
  getFannanPoint: "Get artBeatz Point.",
  NOPOINT: "No Point Available.",
  AddedFannan: "Added artBeatz Point Successfully.",
  sufficient: "Opps,You don't have sufficient point for this request.",
  PayoutRequest: "Your payout request successfully.you have to wait sometime for approval by admin.",
  GetAllTrans: "Get All Transaction history.",
  updatePrivate: "Update Private Status.",
  makeMoney: "Pay your amount by user.",
  alreadyRegistered: "Already email id exist.Please use another email.",
  addFav: "Add favourite.",
  unFav: "Remove favourite.",
  getAllGallery: "Get all gallery.",
  jobMsg: "Hey, New job available in your area. Please check find job section.",
  changedEmail: "Your Email has been changed.",
  getAllData: "Get all user data.",
  GET_ALL_PACKAGES: "Load Packages Successfully",
  SUBSCRIPTION_SUCCESS: "You have successfully subscribed",
  GET_ALL_MY_SUBSCRIPTION: "Load Subscription History Successfully",
  GET_IS_NOT_SUBSCRIBED: "You have not subscribed yet!",
  GET_IS_SUBSCRIBED: "You are subscribed",
  ARTIST_NOT_FOUND: "Artist not found!"

}