module.exports = {
  //email setting
  AUTH_KEY: "205521AaBNspcwGS5ab512aa",
  FROM: "info@samyotech.com",
  //Verified Url
  VERIFIED_EMAIL: "http://159.65.157.119:4005/verify-email/",
  UPDATE_EMAIL: "http://159.65.157.119:4005/update_email/",

  update_email_msg: "<br/>Do you want to change the email_id so please click this link. ",
  logout: "تسجيل الخروج بنجاح",
  ACCOUNT_STATUS: "يبدو أنه تم إلغاء تنشيط حسابك من المسؤول. يرجى الاتصال بالمسؤول لاستئناف حسابك. شكرا لكم.",
  chkfield: "التحقق من جميع الحقول",
  VerifyEmail: "يرجى التحقق من معرف البريد الإلكتروني الخاص بك.",
  ERR: "يرجى المحاولة مرة أخرى بعد بعض الوقت.",
  USER_NOT_FOUND: "المستخدم غير موجود",
  DEACTIVATEUSER: "أنت لست مستخدمًا نشطًا",
  getUserData: "الحصول على ملف تعريف المستخدم",
  DeleteAcc: "حذف الحساب.",
  getAllWork: "احصل على كل العمل",
  ALL_NOTIFICATION: "الحصول على جميع الإخطارات ",
  updateEmail: "تحديث البريد الإلكتروني بنجاح.",
  updateMobile: "تحديث رقم الجوال بنجاح.",
  LOGINSUCCESSFULL: "تسجيل الدخول بنجاح ",
  //LOGINSUCCESSFULL:"Login successfully.",
  deleteGallery: "حذف معرض بنجاح",
  Nocoupon: "لا توجد قسيمة متوفرة.",
  getAllCoupon: "احصل على جميع القسائم.",
  EMAILALERADY: "معرف البريد الإلكتروني مسجل بالفعل. يرجى استخدام معرف بريد إلكتروني مختلفمعرف البريد الإلكتروني مسجل بالفعل. يرجى استخدام معرف",
  REG_SUCCESS: "تم التسجيل بنجاح. لقد أرسلنا لك رسالة بريد إلكتروني للتحقق من معرف البريد الإلكتروني الخاص بك قبل تسجيل الدخول",
  CHECK_YOUR_EMAIL: "تحقق من معرف بريدك الإلكتروني.",
  User_INFO_UPDATE: "تم تحديث معلومات المستخدم.",
  ACCOUNT_STATUS: "يبدو أنه تم إلغاء تنشيط حسابك من المسؤول. يرجى الاتصال بالمسؤول لاستئناف حسابك. شكرا لكم.",
  NO_VALUE_SEND: "لا توجد قيمة ترسل.",
  PASS_NT_MATCH: "رمز مرور خاطئ.",
  FORGETPASS: "لقد تم تغيير كلمة المرور الخاصة بك بنجاح.",
  NOT_RESPONDING: "الرجاء معاودة المحاولة في وقت لاحق.",
  NOT_MATCHED: "كلمة المرور القديمة غير متطابقة.",
  PWD_CNG: "الرجاء التحقق من بريدك الإلكتروني بحثًا عن كلمة المرور المحدثة.",
  EMAILIDNOTFOUND: "لم يتم العثور على معرف البريد الإلكتروني",
  PROFILE_UPDATED: "تم تحديث الملف الشخصي بنجاح",
  GET_CAT: 'الحصول على جميع الفئات.',
  deleteService: "الخدمة المحذوفة",
  NO_CAT: 'لا توجد بيانات متاحة.',
  NOEMAIL: "البريد الإلكتروني غير موجود.",
  POST_JOB: "تمت إضافة الوظيفة بنجاح.",
  ADD_RATING: "تم التقييم بنجاح.",
  // NOT_RESPONDING: "Please try again later.",
  JOB_UPDATE: 'تم تحديث الوظيفة بنجاح.',
  JOB_DELETE: 'تم حذف الوظيفة بنجاح.',
  ARTIST_WORKING: "فنان يعمل حاليًا في هذه الوظيفة.",
  ADD_GALLERY: "تم تحديث المعرض بنجاح.",
  Zero: 0,

  One: 1,
  TWo: 2,
  NOT_RESPONDING: "الرجاء معاودة المحاولة في وقت لاحق.",
  JOB_START: "بدء العمل بنجاح.",
  JOB_UPDATE: 'تم تحديث الوظيفة بنجاح.',
  JOB_DELETE: 'تم حذف الوظيفة بنجاح.',
  JOB_CONFIRM: 'أكد العمل بنجاح.',
  JOB_REJECTED: 'تم رفض الوظيفة بنجاح.',

  APPLIED_JOB: "يتم تطبيق عملك من قبل الفنان.",
  Applied_job_title: "يتم تطبيق عملك من قبل الفنان.",
  APPLIED_JOB_MSG: "تطبق على عملك.",
  base_url_image: "http://159.65.241.51/",
  base_url: "http://159.65.241.51/",
  status: "status",
  message: "message",
  AlredyRegister: "مستخدم مسجل بالفعل.",
  USER: "user",
  GET_JOB: 'الحصول على جميع الوظائف.',
  MSGUPDATEDPASSWORD: "كلمة المرور المحدثة هي",
  TIECKET_GENERATED: "كلمة المرور المحدثة هي",
  MY_TIECKET: "تم إنشاء التذكرة بنجاح.",
  ADD_COMMENT: "تم إنشاء التذكرة بنجاح.",
  getAllRating: "الحصول على جميع التقييمات.",
  getAllService: "الحصول على جميع الخدمات.",
  NODATA: 'لا تتوافر بيانات.',
  Notification_type: "10001",
  Accept_Job: "10002",
  Delete_job: "10003",
  Complete_job: "10004",
  Start_job: "10005",
  end_job: "10006",
  reject_job_type: "10008",
  post_job_type: "1111",
  chat_type1: "20001",
  Direct_Job: "10009",
  Applied_job: "10010",
  invoice_type: "10011",
  review_type: "10012",
  Apply_job_title: "الوظيفة التطبيقية.",
  START_JOB: "بدء العمل بنجاح.",
  StartJobByArtist: "فنان بدء عملك",
  Direct_Job_msg: "لديك وظيفة جديدة",
  Accept_Job_msg: "يتم قبول عملك من قبل المستخدم.",
  Reject_job: "تم رفض عملك من قبل المستخدم.",
  jobRunning: "وظيفتك تعمل أيضا.",
  Reject_title: "رفض الوظيفة.",
  Invoice_created: "دفع فاتورتك.",
  review_msg: "شخص يمنحك التصنيف",
  review_title: "تقييم",
  end_job_succ: "إنهاء المهمة بنجاح.",
  pending_job: "الحصول على جميع الوظائف المعلقة",
  confirmJob: "الحصول على جميع تأكيد الوظائف",
  incorrectPwd: "الرجاء إدخال كلمة المرور الصحيحة",
  Apply_job: "الحصول على جميع المستخدمين الذين طبقوا هذه الوظيفة",
  Not_Job_Apply: "لا تنطبق على وظيفة العثور على البيانات",
  AccepJotTitle: "وظيفة مقبولة",
  getCompleteJob: "الحصول على جميع الوظائف كاملة",
  getRejectJob: "الحصول على جميع وظائف رفض",
  getDeactivejob: "الحصول على جميع وظائف deactive",
  runningJob: "الحصول على جميع وظائف الجري",
  jobDone: "تم إنجاز المهمة",
  CURRENT_APPOINTMENT: "الحصول على موعد بلدي الحالي",
  GET_ARTIST_NEAR: "الحصول على جميع الفنانين",
  Job_reject: "رفض الوظيفة",
  Job_reject_msg: "تم رفض عملك من قبل المستخدم",
  getAllData: "الحصول على جميع البيانات",
  Completejob: "وظيفة كاملة",

  insufficient: "ليس لديك نقطة كافية للفوترة",
  completeJobMsg: "الانتهاء من عملك من قبل الفنان",
  Delete_job_title: "حذف الوظيفة",
  getAllArtist: "الحصول على كل الفنان",
  Delete_msg: "أنت وظيفة المحذوفة من قبل المستخدم",
  NOT_FOUND_DATA: "لم يتم العثور على البيانات",
  newJob: "وظيفة جديدة",
  startJob: "بدء العمل",
  alreadyCouponUsed: "القسيمة المستخدمة بالفعل",
  ActiveJob: "جميع الوظائف النشطة",

  GetAllInvoice: "الحصول على جميع بيانات الفاتورة",
  //name of the all Apis
  GetInvoice: "/getInvoice",
  GetNearestArtist: "/getNearArtist",
  GetCurrentJob: "/getCurrentJob",
  GetAllActiveJobs: "/getAllActivebookingJob",
  EndJob: "/EndJob",
  StartJob: "/startJob",
  AcceptJobByUser: "/AcceptJobByUser",
  GetJobsAppliedByUser: "/getJobsAppliedUser",
  GetJobsArtist: "/getJobsArtist",
  ApplyJob: "/applyJob",
  GetJobByStatus: "/getJobsByStatus",
  Deletejob: "/deletejob",
  UpdateJob: "/updateJob",
  GetMyJobs: "/getMyJobs",
  PostJob: "/postJob",
  SignUp: "/signUp",
  SignUp1: "/signUpByOnline",
  SignIn: "/signIn",
  changePassword: "/changePassword",
  fogetPassword: "/fogetPassword",
  updateProfile: "/updateProfile",
  checkSocialLogin: "/checkSocialLogin",
  CHAT_HISTORY: "الحصول على سجل الدردشة",

  MSGSENDSUCCESS: "إرسال رسالة بنجاح",
  HELLO: "Hello ",
  REGISTRATION_TXT: "<br/> Thank you for registration with Fannan App. Please click on below link for verify you email address.",
  RGN: "Registration",
  email_update: "Update Email.",
  SIGNATURE: "<br/> Thanks, <br/>Fannan Team",
  FRGPWD: "هل نسيت كلمة المرور",
  All_Coupons: "الحصول على جميع القسائم",
  No_data: "لاتوجد بيانات",
  ADD_SERVICE: "إضافة الخدمة بنجاح",
  getFannanPoint: "الحصول على فنان بوينت",
  NOPOINT: "لا نقطة المتاحة",
  AddedFannan: "تمت إضافة فنان بوينت بنجاح",
  sufficient: "عذراً ، ليس لديك نقطة كافية لهذا الطلب",
  PayoutRequest: "طلب دفع تعويضات بنجاح. عليك الانتظار في وقت ما للحصول على موافقة المشرف",
  GetAllTrans: "الحصول على جميع المعاملات التاريخ",
  updatePrivate: "تحديث الوضع الخاص",
  makeMoney: "تحديث الوضع الخاص",
  alreadyRegistered: "البريد الإلكتروني موجود بالفعل. الرجاء استخدام بريد إلكتروني آخر",
  addFav: "أضف المفضلة",
  unFav: "إزالة المفضلة",
  getAllGallery: "الحصول على كل معرض",
  jobMsg: "مهلا ، وظيفة جديدة متوفرة في منطقتك. يرجى التحقق من العثور على قسم العمل",
  changedEmail: "Your Email has been changed.",
  getAllData: "الحصول على جميع بيانات المستخدم",
  GET_ALL_PACKAGES: "تحميل الحزم بنجاح",
  SUBSCRIPTION_SUCCESS: "لقد تم اشتراكك بنجاح",
  GET_ALL_MY_SUBSCRIPTION: "تحميل سجل الاشتراك بنجاح",
  GET_IS_NOT_SUBSCRIBED: "أنت لم تشترك بعد",
  GET_IS_SUBSCRIBED: "أنت مشترك",
  ARTIST_NOT_FOUND: "الفنان غير موجود"
}